language: php

env:
  - PHALCON_VERSION="2.0.0"

install:
  - tests/memcached.sh

before_script:
  - ./tests/install-php-extension.sh ${PHALCON_VERSION}
  - php -r 'echo \Phalcon\Version::get()."\n";'
  - composer self-update
  - composer update

php:
  - 5.4

script:
  - phpunit --configuration tests/phpunit.xml.dist --coverage-clover=coverage.clover

services:
  - memcached

matrix:
  allow_failures:
    - composer
    - phpunit
    - ext-phalcon